version: "3.8"
services:
  frontend:
    image: public.ecr.aws/t0t2o6x5/academy/simple-frontend:latest
    container_name: frontend
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://${CORS_URL:-localhost}:8080
    ports:
      - "3000:3000"

  backend:
    image: public.ecr.aws/t0t2o6x5/academy/simple-webservice:latest
    container_name: webservice
    depends_on:
      - db
    environment:
      CORS_URL: http://${CORS_URL:-localhost}:3000
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgresdb
    ports:
      - "8080:8080"

  db:
    image: postgres:13.4
    container_name: postgresdb
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  pgadmin:
