version: "3.8"
services:
  frontend:
    image: academy/simple-frontend:latest
    container_name: frontend
    depends_on:
      - backend
      - db
    ports:
      - "3000:8080"

  backend:
    image: academy/simple-webservice:latest
    container_name: webservice
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgresdb
    ports:
      - "8080:8080"

  db:
    image: postgres:13.4
    container_name: postgresdb
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  pgadmin:
